### ISSUE TITLE
should be "abnormal cytokinesis"

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3453] opened 2019-05-17 14:52 UTC
elongated multinucleate multiseptate vegetative cell, single septa between nuclei (FYPO:0001253)

**Comment by ValWood** [comment] 2019-05-17 14:55
and
multinucleate multiseptate cell

**Comment by mah11** [comment] 2019-05-31 10:30
Any link would have to be one of the "output" ones (for now; then we'll see what the upheno overhaul does with the lot), probably structure/cell term output_of cytokinesis term.

Does seeing a multinucleate multiseptate vegetative cell *always* imply abnormal cytokinesis? If so, I'll use output_of. Then we should check which other terms that brings along by transitivity, and which ones will need me to add output_of abnormal cytokinesis manually.

**Comment by ValWood** [comment] 2019-05-31 10:32
> Does seeing a multinucleate multiseptate vegetative cell always imply abnormal cytokinesis? 

in fission yeast yes.

**Comment by mah11** [comment] 2019-05-31 10:48
Hang on, I just realized this is a duplicate of #3408, and in that ticket I said I didn't want to have to add ontology links manually if there was a way to improve querying instead. It's not only tedious, it's a bit ontologically dodgy (as explained in the other ticket).

Moving further comments to #3409.

**Closed by mah11** 2019-05-31 10:48 UTC
Labels: duplicate
