### ISSUE TITLE
silencing terms will need new logical definitions

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3635] opened 2020-03-13 16:41 UTC
All of the GO "chromatin silencing' terms will be merged into  correspondeing "heterochromatin assembly" terms.

Therefore, andy logical desf which use them will need to be defined differnetly (i'm not sure how but mostly probably
"negattive regulation of  gene expression" and "heterochromatin"

The complete list is here:
https://docs.google.com/spreadsheets/d/1a-iWPesVFSTpSgRIx9p8D5D5BLNjzMGI8wHVmqvWu5Q/edit#gid=0

**Comment by mah11** [comment] 2020-03-17 10:15
ontology checks done upon release would flag anything like this

**Comment by ValWood** [comment] 2020-03-17 10:44
Ah OK, I wondered if it did.
Do merges generally create a lot of rejigging?

**Comment by mah11** [comment] 2020-03-18 10:23
The linked spreadsheet doesn't have anything about merging "chromatin silencing' terms into  "heterochromatin assembly" terms. Is it the correct one? (Whether it is or not, it's not easy to follow what the actual proposed changes are in it, but if it's the wrong one that's not a problem for FYPO.)

**Comment by mah11** [comment] 2020-03-18 10:26
> Do merges generally create a lot of rejigging?

Fortunately, GO merges that affect FYPO have been rare enough that I don't have a lot of experience to draw on. My sense is that it depends on the terms involved as well as how many FYPO terms are affected.

Aside: Actually doing term merges is about to become a much bigger PITA, when we switch to using Protege.

**Comment by mah11** [comment] 2020-03-18 10:31
Or has that spreadsheet got some weird filtering imposed? I just noticed that the line number column jumps from 2 to 28, then 35, 41, 49 ... best get it fixed if you want anyone to be able to use it.

**Comment by mah11** [comment] 2020-03-18 10:33
In any case, it'll be far easier to find the affected terms, and see how to update FYPO, after the GO work is done.

**Comment by ValWood** [comment] 2020-03-18 12:51
yeah I think that spreadsheet has some weird filtering. I think it's only for Pascale to work from. I thought I would give you a heads up, but it sounds as though it won't make so much difference

**Comment by mah11** [comment] 2020-03-23 09:37
There's now a relevant GO ticket - https://github.com/geneontology/go-ontology/issues/19112

**Comment by mah11** [comment] 2020-03-23 09:41
@ValWood Question: Do you want to change the *phenotype* terms to "heterochromatin assembly" or do you want to leave the FYPO term names unchanged, and then use "chromatin silencing" phenotypes to infer a role in or effect on GO BP heterochromatin assembly?

If the FYPO terms should still use "chromatin silencing" then maybe they can't use GO BP logical defs ... I'd have to have a think.

**Comment by mah11** [comment] 2020-03-23 10:00
affected
GO:0006343	FYPO:0007223
GO:0030702	FYPO:0000147
GO:0030702	FYPO:0002360
GO:0030702	FYPO:0002834
GO:0030702	FYPO:0003411
GO:0030702	FYPO:0004541
GO:0030702	FYPO:0005071
GO:0030702	FYPO:0006995
GO:0030466	FYPO:0000156
GO:0030466	FYPO:0002336
GO:0030466	FYPO:0002827
GO:0030466	FYPO:0004376

**Comment by ValWood** [comment] 2020-03-23 10:07
The phenotypes should still. be "silencing". So the logical defs will now be incorrect. Go won't have the concept of 'silencing'  (phenotype) I hope it isn't too many :(

**Comment by mah11** [comment] 2020-03-23 10:09
OK, that does at least make it an easy fix - ditch the LDs. It's only the dozen terms in my previous comment. I'll implement when the GO work is actually done.

**Comment by ValWood** [comment] 2020-03-23 10:11
I thought there were bzillions of silencing terms. I think there are  more GO term changes  on the way...

**Comment by mah11** [comment] 2020-03-23 10:17
/me goes and counts ...

Ah, 46 terms with "silencing" in the name. For the list above I only looked at the IDs Pascale put in the GO ticket (19112), so presumably more will be on the way. Not much more work to deal with the lot all at once (I'll still wait for the first wave of changes to hit GO, though).

There are a handful of FYPO terms that say "gene silencing" and refer to GO:0016458. Do you know whether anything will happen to that one?

**Comment by ValWood** [comment] 2020-03-23 13:46
I think GO:0016458 is safe as it is post-transcriptional.  Well at least right now. There may be rejigging but I expect it will be more minor.

**Comment by colinlog** [comment] 2020-03-24 09:18
Would something along the lines of an arbitarry split whereby;

'Silencing can only be a BP and it has amongst its children 'Heterochromatin assembly / maintenance' that are MF, or at the very least BPs with proteins that have known relevant MF such as histone chaperone, histone modification, modified histone biding, etc...' 

work-out in the logical definitions, phenotypes and other places where the anticipated simplification of the heterochromatin branches of GO is anticipated to perhaps be problematic?

**Comment by mah11** [comment] 2020-03-24 09:33
@colinlog If I understand correctly, Val's point is that silencing is a phenotype, and therefore belongs in ontologies like FYPO rather than in GO. It's not really a matter of splitting between MF and BP in GO.

**Comment by colinlog** [comment] 2020-03-24 10:17
'Silencing defect' or probably 'suppression/enhancement of position effect variegation caused by translocations close to centromeres or telomeres' is then a set of phenotypes (the famous polycomb mutants and all the beautiful biology they underlie), as would be some homeotic transformation phenotypes. ***But*** the process silencing is synonymous to a number of GO processes amongst which heterochromatin assembly and maintenance, no?

**Comment by ValWood** [comment] 2020-03-24 11:20
@colinlog But we agreed  on the last that transcription call that   BP 'chromatin silencing'  as currently in GO?
i.e./ Repression of transcription by altering the structure of chromatin, e.g. by conversion of large regions of DNA into an inaccessible state often called heterochromatin.
is equivalent to  BP 'heterochromatin assembly' 

This is how it has been used so I believe the merges are safe? If not you should alert @pgaudet now as the merges are in progress (today hopefully)

NOTE that this is the FYPO tracker. You have hopped into a new species ;) We are describing fission yeast phenotypes here (PomBase makes detailed phenotype annotation to attach phenotypes with specific genotypes and conditions)

This  effort is orthogonal to GO. But we use GO normal processes in FYPO logical definitions.
In FYPO we will still have 'chromatin silencing' phenotypes to describe assays where a reporter gene is inserted into constitutive heterochromatin and  derepression is observed.
But for GO we do not need to worry about this ticket. ;)

**Comment by colinlog** [comment] 2020-03-24 11:57
@Pascale Gaudet <pascale.gaudet@sib.swiss> no problem with our decision. I
just got triggered by the remark thatthe word silencing would fully
disappear. This sounds crazy. but it is a matter of synonyms, ot of
refactoring, which is very sensible and should not be stopped!!!

**Comment by pgaudet** [comment] 2020-03-24 11:59
please dont enter email addresses ! the trackers are public .... I dont need more spam mail 
Tagging my github handle is sufficient (@pgaudet) 

@colinlog Can you please edit & delete ?

**Comment by pgaudet** [comment] 2020-03-24 12:00
@colinlog I think 'silencing' should remain as a synonym. This also avoids creating terms that we have previously obsoleted.

**Comment by ValWood** [comment] 2020-03-24 12:05
removed

**Comment by colinlog** [comment] 2020-03-24 16:01
I agree

**Comment by mah11** [comment] 2020-03-31 18:16
I've done the bulk of the work, so I'll close this and open one new ticket for one outstanding bit (which is waiting for work on the relevant GO term). New tickets for anything else you spot too, please.

edit file: 1406da4f08419332f5edf314d3b32c69f3d7202f
release: e78a27623827f37533246f6b61131aff7b85e8ed

**Closed by mah11** 2020-03-31 18:16 UTC
Labels: QC, other ontology change, waiting for external change (e.g. GO fix)

**Comment by ValWood** [comment] 2020-03-31 19:36
Great. I have been avoiding sending out CC sessions/reminder  for chromatin related stuff because I think the big GO issues are one  (of a few) reasons that this  group does not curate much. I hope these changes (mainly to GO ) will  help to make the curation much easier/clearer.
