### ISSUE TITLE
PMID:33410907

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3891] opened 2021-01-22 14:39 UTC
+ normal protein localization to chromatin  during cellular response to oxidative stress
+ decreased protein phosphorylation during cellular response to oxidative stress
+ increased protein-protein interaction during cellular response to oxidative stress
+ increased cellular reactive oxygen species during cellular response to oxidative stress

**Comment by mah11** [comment] 2021-01-27 14:43
normal protein localization to chromatin during cellular response to oxidative stress FYPO:0007619
  decreased protein phosphorylation during cellular response to oxidative stress FYPO:0007620
  increased protein-protein interaction during cellular response to oxidative stress FYPO:0007621
  increased cellular reactive oxygen species level during cellular response to oxidative stress FYPO:0007622

**Comment by ValWood** [comment] 2021-01-28 11:54
didn't see
normal protein localization to chromatin during cellular response to oxidative stress FYPO:0007619
under
normal protein localization to chromatin during vegetative growth

**Comment by mah11** [comment] 2021-01-28 12:19
That makes no %#$^&@ sense. FYPO:0007619 uses the same logical definition pattern as FYPO:0002979 (the equivalent with MMS), but `is_a FYPO:0001509` is being inferred only for FYPO:0002979. I have no idea why.

@matentzn any clue? (before I go in and assert the link)

**Comment by ValWood** [comment] 2021-01-28 12:26
Just  double check, I didn't miss it did I (I double checked but I couldn't see it and there didn't seem to be a term it could be hidden under...)

**Comment by matentzn** [comment] 2021-01-28 14:58
The problem is with Protege:
https://github.com/protegeproject/protege/issues/990#issuecomment-766169140

What happened is that you used the wrong quality (from BFO instead of PATO) for this eq - something you can only see in Protege if you switch to `View->Render by short name`. Its very annoying!! Please put some weight behind my comment on the protege issue as well if you like - I think there is a good chance it will be fixed soon.

In the meantime:
https://github.com/pombase/fypo/pull/3894


Once in a while, just run:

```
sh run.sh make fix_quality_issue -B
```

What this does is: replacing all your accidental uses of BFO:quality with PATO:quality.
Note: the diff will be unintelligible after running this, because of OBO format - but you can run and then open in protege, then run the reasoner to confirm.

**Comment by mah11** [comment] 2021-01-28 15:05
Thanks!!! There is just. no. way. I would ever have figured that out on my own. I find it hugely annoying that I can't use IDs to build LDs in Protege ... and now I have a new reason.

**Comment by matentzn** [comment] 2021-01-28 15:08
One workflow that approximates this is:
Navigate to term normally:
switch to `Render by short name` to write the EQ.
switch back to `Render by label`. But obviously better to fix the software.. Please (!) share your frustration (in a diplomatic way) in that ticket :)

**Comment by mah11** [comment] 2021-02-03 11:02
I ran Nico's script and that seems to have fixed it - we now get the expected inference. Hooray!

**Closed** 2021-02-03 16:21 UTC
Labels: community curation, new ontology term
